version: "3"

services:
    mc:
      restart: always
      image: itzg/minecraft-server
      ports:
          - 25565:25565
      environment:
          MODPACK: "https://siyuanyan.net/commupack.zip"
          MOTD: "§lEqual§r §2Equal§r §nEqual§r §oEqual§r §1Equal §3Equal"
          EULA: "TRUE"
          VERSION: "1.18.1"
          MAX_THREADS: "0"
          OPS: "2513034344e04f099e8e8ac79b8b27f5,1123d8229e6f4fbc87d0665549e729e7"
          MEMORY: "2G"
          SEED: "200"
          ALLOW_FLIGHT: "TRUE"
          SIMULATION_DISTANCE: "32"
          VIEW_DISTANCE: "32"
          tty: "TRUE"
          TYPE: "FORGE"
          stdin_open: "TRUE"
      volumes: 
          - /opt/mc:/data

